"use client"

import { useState, useEffect, useCallback } from 'react'
import { supabaseAny as supabase } from '@/lib/supabase'
import {
  Lightbulb,
  RefreshCw,
  TrendingUp,
  TrendingDown,
  Target,
  Shield,
  AlertTriangle,
  Zap,
  Calendar,
  ChevronDown,
  ChevronUp,
  Sparkles,
  Key,
  Eye,
  EyeOff,
} from 'lucide-react'

interface Tip {
  id: string
  week_of: string
  generated_at: string
  rank: number
  asset: string
  ticker: string | null
  asset_type: string | null
  direction: string
  conviction: string | null
  rationale: string
  catalysts: string | null
  entry_zone: string | null
  exit_strategy: string | null
  stop_loss: string | null
  risks: string | null
  target_return: string | null
  source_signals: string | null
}

export function TipsPanel() {
  const [tips, setTips] = useState<Tip[]>([])
  const [loading, setLoading] = useState(true)
  const [generating, setGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [expanded, setExpanded] = useState<number | null>(null)
  const [apiKey, setApiKey] = useState('')
  const [showKey, setShowKey] = useState(false)

  // Load api key from localStorage
  useEffect(() => {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('trump_tracker_api_key') : null
    if (saved) setApiKey(saved)
  }, [])

  const handleKeyChange = (v: string) => {
    setApiKey(v)
    if (typeof window !== 'undefined') {
      if (v) localStorage.setItem('trump_tracker_api_key', v)
      else localStorage.removeItem('trump_tracker_api_key')
    }
  }

  const fetchTips = useCallback(async () => {
    setLoading(true)
    const { data } = await supabase
      .from('tracker_tips')
      .select('*')
      .order('week_of', { ascending: false })
      .order('rank', { ascending: true })
      .limit(5)

    if (data) setTips(data as unknown as Tip[])
    setLoading(false)
  }, [])

  useEffect(() => { fetchTips() }, [fetchTips])

  const handleGenerate = async () => {
    setGenerating(true)
    setError(null)
    try {
      const res = await fetch('/api/trump-tracker/tips', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ apiKey: apiKey || undefined }),
      })
      const data = await res.json()
      if (!data.success) {
        setError(data.error || 'Failed to generate tips')
      } else {
        await fetchTips()
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Request failed')
    }
    setGenerating(false)
  }

  const weekOf = tips[0]?.week_of
  const generatedAt = tips[0]?.generated_at

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-bold text-card-foreground flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-amber-500" />
            Tips of the Week
          </h2>
          <p className="text-[10px] text-muted-foreground mt-0.5 flex items-center gap-1.5">
            <Sparkles className="w-2.5 h-2.5" />
            Macro trader AI · Based on insider trading signals
            {weekOf && (
              <>
                <span className="mx-1">·</span>
                <Calendar className="w-2.5 h-2.5" />
                Week of {new Date(weekOf).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
              </>
            )}
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={generating}
          className="flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-amber-500 text-white hover:bg-amber-600 transition-colors disabled:opacity-50"
        >
          {generating ? (
            <><RefreshCw className="w-3.5 h-3.5 animate-spin" /> Generating...</>
          ) : (
            <><Zap className="w-3.5 h-3.5" /> Generate New Tips</>
          )}
        </button>
      </div>

      {/* Strategy summary */}
      <div className="p-3 rounded-lg border border-amber-500/20 bg-amber-500/5">
        <p className="text-[11px] text-muted-foreground leading-relaxed">
          <span className="font-semibold text-amber-500">Strategy:</span> 5 high-conviction trade ideas generated by a macro-trader AI
          analyzing Trump family, Congress, and White House insider activity. Target ~2%/week per trade with controlled risk
          (asymmetric risk/reward, clear stop-loss, defined exit).
        </p>
      </div>

      {/* API Key input */}
      <div className="p-3 rounded-lg border border-border bg-card">
        <label className="text-[10px] font-semibold text-muted-foreground uppercase mb-1.5 flex items-center gap-1">
          <Key className="w-2.5 h-2.5" />
          Anthropic API key (stored locally in your browser)
        </label>
        <div className="relative">
          <input
            type={showKey ? 'text' : 'password'}
            value={apiKey}
            onChange={e => handleKeyChange(e.target.value)}
            placeholder="sk-ant-..."
            className="w-full pr-9 pl-3 py-2 text-xs rounded-lg border border-border bg-background text-foreground placeholder:text-muted-foreground/50 focus:outline-none focus:ring-2 focus:ring-amber-500/20 focus:border-amber-500 font-mono"
          />
          <button
            type="button"
            onClick={() => setShowKey(!showKey)}
            className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
          >
            {showKey ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
          </button>
        </div>
        <p className="text-[10px] text-muted-foreground mt-1.5">
          Get a key at <a href="https://console.anthropic.com/settings/keys" target="_blank" rel="noopener noreferrer" className="text-amber-500 hover:underline">console.anthropic.com</a>. Never shared with the server except to generate tips.
        </p>
      </div>

      {/* Error */}
      {error && (
        <div className="p-3 rounded-lg border border-red-500/30 bg-red-500/5 text-xs text-red-400">
          {error}
        </div>
      )}

      {/* Tips list */}
      {loading ? (
        <div className="flex items-center justify-center py-10 text-muted-foreground">
          <RefreshCw className="w-4 h-4 animate-spin mr-2" />
          <span className="text-sm">Loading tips...</span>
        </div>
      ) : tips.length === 0 ? (
        <div className="text-center py-12 rounded-xl border border-dashed border-border">
          <Lightbulb className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
          <p className="text-sm font-medium text-card-foreground">No tips yet</p>
          <p className="text-xs text-muted-foreground mt-1 max-w-xs mx-auto">
            Click &quot;Generate New Tips&quot; to run the macro-trader AI on the latest tracker data
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {generatedAt && (
            <p className="text-[10px] text-muted-foreground">
              Generated {new Date(generatedAt).toLocaleString()}
            </p>
          )}
          {tips.map(tip => (
            <TipCard
              key={tip.id}
              tip={tip}
              expanded={expanded === tip.rank}
              onToggle={() => setExpanded(expanded === tip.rank ? null : tip.rank)}
            />
          ))}
        </div>
      )}
    </div>
  )
}

function TipCard({ tip, expanded, onToggle }: { tip: Tip; expanded: boolean; onToggle: () => void }) {
  const isLong = tip.direction.toLowerCase() === 'long'
  const convictionColor =
    tip.conviction === 'high' ? '#10b981' :
    tip.conviction === 'medium' ? '#f59e0b' :
    '#6b7280'

  return (
    <div className="rounded-xl border border-border bg-card overflow-hidden">
      {/* Header */}
      <button onClick={onToggle} className="w-full p-4 flex items-center gap-3 hover:bg-muted/20 transition-colors text-left">
        {/* Rank */}
        <div className={`flex items-center justify-center w-8 h-8 rounded-lg flex-shrink-0 font-bold text-sm ${
          tip.rank === 1 ? 'bg-amber-500/20 text-amber-500' :
          tip.rank === 2 ? 'bg-slate-400/20 text-slate-300' :
          tip.rank === 3 ? 'bg-orange-600/20 text-orange-500' :
          'bg-muted text-muted-foreground'
        }`}>
          #{tip.rank}
        </div>

        {/* Asset info */}
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-base font-bold text-card-foreground">
              {tip.ticker || tip.asset}
            </span>
            {tip.ticker && (
              <span className="text-xs text-muted-foreground">{tip.asset}</span>
            )}
            <span className={`flex items-center gap-0.5 text-[10px] font-bold px-1.5 py-0.5 rounded-full ${
              isLong ? 'bg-green-500/15 text-green-500' : 'bg-red-500/15 text-red-500'
            }`}>
              {isLong ? <TrendingUp className="w-2.5 h-2.5" /> : <TrendingDown className="w-2.5 h-2.5" />}
              {tip.direction.toUpperCase()}
            </span>
            {tip.conviction && (
              <span
                className="text-[10px] font-bold px-1.5 py-0.5 rounded-full"
                style={{ backgroundColor: convictionColor + '20', color: convictionColor }}
              >
                {tip.conviction.toUpperCase()}
              </span>
            )}
            {tip.target_return && (
              <span className="text-[10px] font-semibold text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                Target {tip.target_return}
              </span>
            )}
          </div>
          <p className="text-xs text-muted-foreground mt-1 line-clamp-1">
            {tip.rationale}
          </p>
        </div>

        {/* Chevron */}
        {expanded ? (
          <ChevronUp className="w-4 h-4 text-muted-foreground flex-shrink-0" />
        ) : (
          <ChevronDown className="w-4 h-4 text-muted-foreground flex-shrink-0" />
        )}
      </button>

      {/* Expanded details */}
      {expanded && (
        <div className="px-4 pb-4 pt-0 space-y-3 border-t border-border/50">
          {/* Rationale */}
          <Section icon={Lightbulb} label="Rationale" content={tip.rationale} color="#f59e0b" />

          {/* Catalysts */}
          {tip.catalysts && (
            <Section icon={Zap} label="Catalysts" content={tip.catalysts} color="#3b82f6" />
          )}

          {/* Entry & Exit */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
            {tip.entry_zone && (
              <MiniBox icon={Target} label="Entry" value={tip.entry_zone} color="#10b981" />
            )}
            {tip.exit_strategy && (
              <MiniBox icon={TrendingUp} label="Exit" value={tip.exit_strategy} color="#3b82f6" />
            )}
            {tip.stop_loss && (
              <MiniBox icon={Shield} label="Stop-loss" value={tip.stop_loss} color="#ef4444" />
            )}
          </div>

          {/* Risks */}
          {tip.risks && (
            <Section icon={AlertTriangle} label="Risks" content={tip.risks} color="#ef4444" />
          )}

          {/* Source signals */}
          {tip.source_signals && (
            <div className="p-3 rounded-lg bg-muted/30 border border-border/50">
              <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-1 flex items-center gap-1">
                <Sparkles className="w-2.5 h-2.5" />
                Insider signals
              </p>
              <p className="text-[11px] text-card-foreground leading-relaxed">{tip.source_signals}</p>
            </div>
          )}
        </div>
      )}
    </div>
  )
}

function Section({ icon: Icon, label, content, color }: {
  icon: typeof Lightbulb
  label: string
  content: string
  color: string
}) {
  return (
    <div>
      <p className="text-[10px] font-semibold uppercase mb-1 flex items-center gap-1" style={{ color }}>
        <Icon className="w-2.5 h-2.5" />
        {label}
      </p>
      <p className="text-[11px] text-card-foreground leading-relaxed">{content}</p>
    </div>
  )
}

function MiniBox({ icon: Icon, label, value, color }: {
  icon: typeof Lightbulb
  label: string
  value: string
  color: string
}) {
  return (
    <div className="p-2 rounded-lg border border-border bg-muted/20">
      <div className="flex items-center gap-1 mb-0.5">
        <Icon className="w-2.5 h-2.5" style={{ color }} />
        <span className="text-[9px] font-semibold uppercase text-muted-foreground">{label}</span>
      </div>
      <p className="text-[11px] font-medium text-card-foreground">{value}</p>
    </div>
  )
}
